# Generated by Django 4.1.3 on 2022-12-01 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asociacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'unique': 'Nombre de usuario no disponible.'}, max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('apellidos', models.CharField(max_length=40, unique=True)),
                ('administrador', models.BooleanField(default=False)),
                ('email', models.EmailField(error_messages={'unique': 'Esta dirección de correo electrónico ya está siendo usada por otra cuenta.'}, max_length=254, unique=True)),
                ('contrasenia', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True)),
                ('contenido', models.TextField(max_length=2000)),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asociacion.usuario')),
            ],
        ),
    ]
