# Generated by Django 4.1.3 on 2022-12-01 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asociacion', '0002_usuario_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='administrador',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
    ]
