# Generated by Django 4.1.3 on 2022-12-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asociacion', '0003_remove_usuario_administrador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(default='', upload_to='uploads/'),
        ),
    ]
